# Neden NumPy?



In [1]:
a = [1,2,3,4]
b = [2,3,4,5]


In [3]:
ab = []

for i in range(0, len(a)):
    ab.append(a[i]*b[i])
ab    
    

[2, 6, 12, 20]

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

 

In [6]:
a * b

array([ 2,  6, 12, 20])

# NumPy Array'i Oluşturmak

In [8]:
import numpy as np

In [9]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [10]:
a = np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [11]:
np.array([3.14,4,2,13])
# sabit tip baskısı 

array([ 3.14,  4.  ,  2.  , 13.  ])

In [12]:
np.array([3.14,4,2,13], dtype = "int")
# sabit tip baskısı 

array([ 3,  4,  2, 13])

# sıfırdan array oluşturma  işlemleri 

In [14]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.ones((3,5) ,dtype = "int")
# 3 satır 5 sütünlük  iki buyutlu
#1 lerden oluşan  bir array oluşturmuş olduk 

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [17]:
np.arange(0,31,3)
# 0 dan 31'e kadar 3er 3er artacak 
#şekilde doğrusal bir dizi oluşturabiliyoruz

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [18]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [19]:
np.random.normal(10, 4, (3,4))
# ortalamsı 10 standart sapması 4
# 3 satırlı 4 sütünlük  iki boyutlu bir array oluşturabiliriz

array([[12.11483449, 12.18575172,  9.43460066,  5.72453414],
       [ 6.57607143, 11.57543858,  4.92129981, 10.23065579],
       [ 7.5537247 ,  8.79829938,  4.43441537, 12.79443092]])

In [20]:
np.random.randint(0,10, (3,3))
# rastgele int türünde...

array([[1, 3, 6],
       [2, 5, 5],
       [4, 7, 4]])

# özellikleri
* **ndim:** _boyut sayısı_
* **shape:** _boyut bilgisi_
* **size:** _toplam eleman sayısı_
* **dtype:** _array veri tipi_

In [22]:
import numpy as np


In [23]:
np.random.randint(10,size = 5)

array([7, 6, 2, 2, 0])

In [24]:
a = np.random.randint(10,size = 8)
a

array([6, 4, 8, 5, 9, 6, 3, 2])

In [25]:
a.ndim

1

In [26]:
a.shape

(8,)

In [27]:
a.size

8

In [28]:
a.dtype

dtype('int32')

In [29]:
b =  np.random.randint(10, size = (3,5))

In [30]:
b

array([[6, 9, 3, 8, 4],
       [0, 1, 5, 4, 8],
       [3, 8, 3, 4, 9]])

In [31]:
b.ndim

2

In [32]:
b.shape

(3, 5)

In [33]:
b.size

15

In [34]:
b.dtype

dtype('int32')

## Yeniden Şekillendirme(Reshaping)

In [36]:
import numpy as np

In [37]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(1,10).reshape((3,3))
# Tek boyutludan 3x3 boyutuna çevirdik

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
a = np.arange(1,10)

In [40]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a.ndim

1

In [42]:
b = a.reshape((2,5))

ValueError: cannot reshape array of size 9 into shape (2,5)

In [ ]:
b.ndim

## Array Birleştirme(Concatenation)

In [ ]:
import numpy as np

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [ ]:
np.concatenate([x,y])

In [ ]:
z = np.array([7,8,9])

In [ ]:
np.concatenate([x,y,z])

### iki boyutluda birleştirme

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])

In [ ]:
np.concatenate([a,a], axis = 0)

### Array Ayırma(splitting)

In [ ]:
import numpy as np 

In [ ]:
x =np.array([1,2,3,99,99,3,2,1])

In [ ]:
np.split(x, [3,5])

In [ ]:
a,b,c = np.split(x, [3,5])

In [ ]:
a

In [ ]:
b

In [ ]:
c

### iki boyutlu ayırma

In [ ]:
m = np.arange(16).reshape(4,4)
m

In [ ]:
np.vsplit(m, [2])

In [ ]:
ust, alt = np.vsplit(m,[3])

In [ ]:
ust

In [ ]:
alt

In [ ]:
m

In [ ]:
np.hsplit(m,[3])

In [ ]:
sag, sol = np.hsplit(m, [2])

In [ ]:
sag

In [ ]:
sol

### Sıralama(Sorting)

In [ ]:
import numpy as np

In [ ]:
v = np.array([2,1,4,3,6])

In [ ]:
v

In [43]:
np.sort(v)

NameError: name 'v' is not defined

In [44]:
v.sort()

NameError: name 'v' is not defined

In [45]:
v

NameError: name 'v' is not defined

### iki boyutlu array sıralama

In [47]:
m = np.random.normal(20,5, (3,3))

In [48]:
m

array([[19.76970707, 20.08563044, 20.57560675],
       [18.06713737, 22.76825286, 17.14588944],
       [17.33397885, 26.38460271, 34.04436701]])

In [49]:
np.sort(m, axis = 1)

array([[19.76970707, 20.08563044, 20.57560675],
       [17.14588944, 18.06713737, 22.76825286],
       [17.33397885, 26.38460271, 34.04436701]])

In [50]:
np.sort(m, axis = 0)

array([[17.33397885, 20.08563044, 17.14588944],
       [18.06713737, 22.76825286, 20.57560675],
       [19.76970707, 26.38460271, 34.04436701]])

### İndex ile Elemanlara  Erişim

In [52]:
import numpy as np

In [53]:
a = np.random.randint(10, size = 9)

In [55]:
a

array([6, 1, 2, 9, 8, 1, 7, 7, 9])

In [56]:
a[0]

6

In [59]:
a[-1]

9

In [60]:
a[0] = 100

In [61]:
a

array([100,   1,   2,   9,   8,   1,   7,   7,   9])

In [62]:
m = np.random.randint(10, size = (3,5))
m

array([[8, 4, 3, 1, 7],
       [9, 8, 6, 1, 7],
       [2, 1, 4, 0, 0]])

In [63]:
m[0,0]

8

In [64]:
m[1,4]

7

In [65]:
m[2,3]

0

In [66]:
m[1,4] = 99

In [67]:
m

array([[ 8,  4,  3,  1,  7],
       [ 9,  8,  6,  1, 99],
       [ 2,  1,  4,  0,  0]])

In [69]:
m[1,4] = 2.2

In [70]:
m

array([[8, 4, 3, 1, 7],
       [9, 8, 6, 1, 2],
       [2, 1, 4, 0, 0]])

### Slicing ile Elemanlara Erişmek(Array alt kümesine Erişmek)

In [72]:
import numpy as np

In [74]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [75]:
a[0:3]

array([20, 21, 22])

In [76]:
a[:3]

array([20, 21, 22])

In [77]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [79]:
a[1::2]

array([21, 23, 25, 27, 29])

In [80]:
a[0::2]

array([20, 22, 24, 26, 28])

In [81]:
a[0::3]

array([20, 23, 26, 29])

### iki boyutlu slice işlemleri

In [362]:
m = np.random.randint(10, size =(5,5))
m

array([[9, 6, 5, 1, 6],
       [1, 3, 7, 3, 6],
       [7, 2, 1, 1, 3],
       [6, 8, 0, 5, 4],
       [7, 3, 1, 7, 8]])

In [370]:
m[:,0]

array([9, 1, 7, 6, 7])

In [356]:
m[:,1]

array([1, 4, 7])

In [88]:
m[:,4]

array([5, 9, 8, 7, 1])

In [89]:
m[0,:]

array([1, 2, 0, 3, 5])

In [90]:
m[0]

array([1, 2, 0, 3, 5])

In [91]:
m[1,:]

array([8, 0, 7, 1, 9])

In [92]:
m

array([[1, 2, 0, 3, 5],
       [8, 0, 7, 1, 9],
       [9, 4, 3, 6, 8],
       [6, 8, 2, 4, 7],
       [5, 3, 7, 7, 1]])

In [93]:
m[0:2,0:3]

array([[1, 2, 0],
       [8, 0, 7]])

In [95]:
m[::,:2]

array([[1, 2],
       [8, 0],
       [9, 4],
       [6, 8],
       [5, 3]])

In [96]:
m[1:3,0:2]

array([[8, 0],
       [9, 4]])

### ALt küme üzerinde  işlem yapmak

In [98]:
import numpy as np 
a = np.random.randint(10, size = (5,5))
a

array([[9, 3, 3, 7, 4],
       [7, 8, 1, 0, 2],
       [8, 4, 2, 0, 4],
       [8, 7, 9, 8, 0],
       [0, 7, 3, 6, 7]])

In [99]:
alt_a = a[0:3, 0:2]
alt_a

array([[9, 3],
       [7, 8],
       [8, 4]])

In [101]:
alt_a[0,0] = 9999
alt_a[1,1] = 888
alt_a

array([[9999,    3],
       [   7,  888],
       [   8,    4]])

In [103]:
# değişiklik(9999,888) sadece alt_a değil a'da da gerçekleşti  
# sadece alt_a'da değişiklik olmasını istiyorsak copy() metodunu kullanırız.
a

array([[9999,    3,    3,    7,    4],
       [   7,  888,    1,    0,    2],
       [   8,    4,    2,    0,    4],
       [   8,    7,    9,    8,    0],
       [   0,    7,    3,    6,    7]])

In [104]:
m = np.random.randint(10, size = (5,5))
m

array([[5, 9, 9, 6, 3],
       [2, 6, 1, 1, 1],
       [6, 4, 6, 5, 6],
       [7, 6, 8, 3, 8],
       [0, 1, 6, 9, 3]])

In [105]:
alt_m = m[0:3, 0:2].copy()
alt_m

array([[5, 9],
       [2, 6],
       [6, 4]])

In [106]:
alt_m[0,0]= 99
alt_m = alt_m * 2
alt_m

array([[198,  18],
       [  4,  12],
       [ 12,   8]])

In [107]:
m

array([[5, 9, 9, 6, 3],
       [2, 6, 1, 1, 1],
       [6, 4, 6, 5, 6],
       [7, 6, 8, 3, 8],
       [0, 1, 6, 9, 3]])

### Fancy İndex ile Elemanlara Erişim

In [113]:
import numpy as np 
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [114]:
v[1]

3

In [115]:
v[5]

15

In [117]:
[v[1], v[5], v[6]]

[3, 15, 18]

In [118]:
al_getir = [1,5,6]


In [121]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [122]:
v[al_getir]

array([ 3, 15, 18])

### iki boyutta fancy

In [125]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [126]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [129]:
m[satir, sutun]

array([1, 5])

### basit index ile fancy index

In [131]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [133]:
m[0,[1,2]]

array([1, 2])

In [134]:
# slice ile fancy

In [135]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

### Koşullu Eleman İşlemleri

In [139]:
import numpy as np
v = np.array([1,2,3,4,5])

In [142]:
v <3

array([ True,  True, False, False, False])

In [143]:
v[v<3]

array([1, 2])

In [144]:
v[v>3]

array([4, 5])

In [146]:
v[v>= 3]

array([3, 4, 5])

In [147]:
v[v== 3]

array([3])

In [149]:
v[v!= 3]

array([1, 2, 4, 5])

In [150]:
v

array([1, 2, 3, 4, 5])

In [151]:
v*2

array([ 2,  4,  6,  8, 10])

In [152]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [153]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [154]:
v**2

array([ 1,  4,  9, 16, 25])

### Matematiksel İşlemler 

In [374]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [376]:
v-1

array([0, 1, 2, 3, 4])

In [378]:
v*5

array([ 5, 10, 15, 20, 25])

In [163]:
#  şu anda bu matematiksel işlemleri yaptığımızda
# (ufunc) adı verilen bir mekanizma çalışıyor.
"""
yani biz aslında yukarıda çarpma işlemini ifade eden * yazmış olsakta
arka tarafata bu işlemler bir dönüştürmeye tabi tutulup numpy'ın içerisinde
yerv alan bazı spesifik fomksiyonlar çalıştırılyor.
"""

"\nyani biz aslında yukarıda çarpma işlemini ifade eden * yazmış olsakta\narka tarafata bu işlemler bir dönüştürmeye tabi tutulup numpy'ın içerisinde\nyerv alan bazı spesifik fomksiyonlar çalıştırılyor.\n"

In [165]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [166]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [168]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [169]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [170]:
v**2

array([ 1,  4,  9, 16, 25])

In [172]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [173]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [174]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [175]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [176]:
# mutlak değer fonksiyonu 
np.absolute(np.array([-3, -5, 6,  8, -9]))

array([3, 5, 6, 8, 9])

In [382]:
np.sin(360)

0.9589157234143065

In [178]:
np.cos(180)

-0.5984600690578581

In [179]:
v  = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [182]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [185]:
# tabanı değiştirdik
np.log2(v)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809])

In [187]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

### İstatiksel Hesaplamalar

In [190]:
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [192]:
# mean  metodu aritmetik ortalamayı hesaplar.
np.mean(v)

5.5

In [194]:
# içindeki değerleri toplar
np.sum(v)

55

In [195]:
np.min(v)

1

In [196]:
np.max(v)

10

In [197]:
# varyans hesaplar
np.var(v)

8.25

In [200]:
# Belirli bir eksenin standart sapmasını döndürür
np.std(v, axis =0)

2.8722813232690143

In [202]:
# Korelasyon katsayısı, iki veya daha fazla değişken arasındaki
# doğrusal ilişkiyi ölçer ve -1 ile 1 arasında bir değer alır.
np.corrcoef(v)

1.0

### NumPy ile İki Bilinmeyenli Denklem Çözümü   

In [206]:
import numpy as np

##### 5* x0 + x1 = 12 
##### x0 +3 *x1 = 10

In [384]:
a = np.array([[5, 1], [1, 3]])
b = np.array([12, 10])


In [386]:
a

array([[5, 1],
       [1, 3]])

In [388]:
b

array([12, 10])

In [390]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])