### Pandas Serisi Oluşturmak

In [127]:
import pandas as pd

In [129]:
pd.Series([10, 88, 3, 4, 5,])

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [131]:
seri = pd.Series([10, 88, 3, 4, 5])
type(seri)

pandas.core.series.Series

In [133]:
# index bilgilerine erişiyoruz
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [134]:
seri.dtype

dtype('int64')

In [137]:
seri.size

5

In [138]:
seri.ndim

1

In [140]:
seri.values

array([10, 88,  3,  4,  5], dtype=int64)

In [142]:
seri.head()

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [143]:
seri.head(3)

0    10
1    88
2     3
dtype: int64

In [145]:
# sondan bakmak
seri.tail(3)

2    3
3    4
4    5
dtype: int64

### index isimlendirmesi

In [149]:
pd.Series([99, 22, 332, 94, 5])

0     99
1     22
2    332
3     94
4      5
dtype: int64

In [151]:
pd.Series([99, 22, 332, 94, 5], index =[1, 3, 5, 7, 9])

1     99
3     22
5    332
7     94
9      5
dtype: int64

In [152]:
pd.Series([99, 22, 332, 94, 5], index =["a", "b", "c", "d", "w"])

a     99
b     22
c    332
d     94
w      5
dtype: int64

In [153]:
seri = pd.Series([99, 22, 332, 94, 5], index =["a", "b", "c", "d", "e"])

In [155]:
seri["a"]

99

In [156]:
seri["a":"d"]

a     99
b     22
c    332
d     94
dtype: int64

### sozluk üzerinden liste oluşturmak 

In [160]:
sozluk = {"reg":10, "log":11, "cart":12}


In [162]:
seri = pd.Series(sozluk)

In [163]:
seri

reg     10
log     11
cart    12
dtype: int64

### iki seriyi birleştirerek seri oluşturma

In [165]:
pd.concat([seri,seri])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

### Eleman İşlemleri

In [169]:
import numpy as np 
import pandas as pd
a =np.array([1, 2, 33, 444, 75]) 
seri = pd.Series(a)
seri

0      1
1      2
2     33
3    444
4     75
dtype: int32

In [170]:
seri[0]

1

In [171]:
seri[0:4]

0      1
1      2
2     33
3    444
dtype: int32

In [173]:
seri = pd.Series([121,200,150,99], 
                 index = ["reg","loj","cart","rf"])

In [174]:
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [178]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [179]:
seri.keys

<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>

In [180]:
list(seri.items())

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [181]:
seri.values

array([121, 200, 150,  99], dtype=int64)

### Eleman Sorgulama

In [185]:
"cart" in seri

True

In [186]:
"Mehmet" in seri

False

In [188]:
# Fancy eleman 

In [189]:
seri[["rf", "reg"]]

rf      99
reg    121
dtype: int64

In [190]:
# reg'in  değerini değiştirdik.
seri["reg"] = 130

In [192]:
seri["reg"]

130

In [194]:
seri["reg":"cart"]

reg     130
loj     200
cart    150
dtype: int64

### Pandas DataFarame Oluşturma

##### pandas DataFrame: Yapısal bir  veri tipidir excel veri yapısına  benzerdir.
##### NumPy  Fixtype yani sabit veri tipli bir veri yapsı dolayısıyle içerisinde kategorik değişkenleri ve sürekli deişkenleri bir arada
##### tutup bunlar üzerinde işlem yapmak konusunda çokta başarılı değil. veri manipülasyonu
##### veri analizi anlamında ihtiyaç duyulan ileri seviye manipülatif işlemler cevap veremiyor. bu sebeple Pandas'a geçmiş olduk.
##### dolayısıya biraz daha teorik yapılar için NumPy'ı düşünebiliriz Pandas  DataFrame Yapısı ise daha analitik anlamda makine öğrenmesi modellerine veri setleri olarak düşünebiliriz.


In [196]:
import pandas as pd

In [200]:
l =[1,2,39,67,90] 

In [202]:
l

[1, 2, 39, 67, 90]

In [203]:
pd.DataFrame(l,columns =["degisken_ismi"],index =["a", "b", "c", "d", "w"])

degisken_ismi
a              1
b              2
c             39
d             67
w             90

In [210]:
import numpy as np
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [213]:
pd.DataFrame(m, columns = ["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [219]:
var4_data = (df["var1"] + df["var2"] + df["var3"]) / 3



NameError: name 'df' is not defined

In [221]:
df.insert(1, "var4", var4_data)

NameError: name 'df' is not defined

#### df(DataFrame) isimlendirme

In [ ]:
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df.head()

In [ ]:
df.columns

In [ ]:
df.columns = ("deg1","deg2","deg3")

In [ ]:
df

In [ ]:
type(df)

In [ ]:
df.axes

In [ ]:
df.shape

In [ ]:
df.ndim

In [ ]:
df.size

In [ ]:
df.values

In [ ]:
# DataFrame tipinfe olan veri yapısının içerisinden sadece değerleri--
# çekip bunları numPy array'ına  yani (ndarray) nesnesine çevirdi.
type(df.values)

In [ ]:
df.head()

In [ ]:
df.tail(1)

In [ ]:
a = np.array([1,2,3,4,5])

In [ ]:
pd.DataFrame(a, columns = ["deg1"])

### Eleman İşlemleri

In [ ]:
import numpy as np

s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [ ]:
sozluk = {"var1": s1, "var2": s2, "var3": s3}

In [ ]:
sozluk

In [ ]:
df = pd.DataFrame(sozluk)

In [ ]:
df

In [ ]:
df[0:1]

In [ ]:
df.index

In [ ]:
df.index = ["a","b","c","d","e"]

In [ ]:
df

In [ ]:
df["c":"e"]

### Silme

In [ ]:
df.drop("a", axis =0)

In [ ]:
df.drop("var2", axis =1)

In [ ]:
df

In [ ]:
"""
veri setinin ana yapısı üzerinde bir değişiklik olmadı
eğer ben a'nın silinmiş olduğu dataframe'i yeni DataFrame olarak tanımlamak 
istersem bu dataframe'i baştan tanımlayabilirim yada 
pandas'ın (inplace) argümanını kullanırım.

"""
df.drop("a", axis = 0, inplace = True)


In [ ]:
df

In [ ]:
# fancy

In [ ]:
l = ["c","e"]

In [ ]:
df.drop(l, axis = 0)

In [ ]:
# değişkenler için

In [ ]:
df

In [ ]:
"var1" in df

In [ ]:
l = {"var1","var4","var2"}

In [ ]:
for i in l:
    print(i in df)

In [ ]:
df

In [ ]:
df["var1"]

In [ ]:
df["var4"] = df["var1"] / df["var2"]

In [ ]:
df

In [ ]:
#değişken silmek
df.drop("var4", axis = 1)

In [ ]:
df

In [ ]:
df.drop("var4", axis = 1, inplace = True)

In [ ]:
df

In [ ]:
l = ["var1", "var2"]

In [ ]:
df.drop(l, axis  = 1)

### Gözlem ve değişken Seçimi:
##### loc & iloc

In [ ]:
import numpy as np
import pandas as pd

m = np.random.randint(1,30, size =(10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

##### loc: tanımlandığı şekli ile seçim yapmak için kullanılır.

In [ ]:
df.loc[0:3]

##### iloc: alışık olduğumuz indexleme mantığı ile seçim yapar. 

In [ ]:
df. iloc[0:3]

In [ ]:
df.iloc[0,0]

In [ ]:
df.iloc[:3,:2]

In [ ]:
df.loc[0:3,"var3"]

In [ ]:
df.iloc[0:3,"var3"]

In [ ]:
df.iloc[0:3, 1:3]

In [ ]:
df.iloc[0:3]["var3"]

### Koşullu Eleman İşlemleri 

In [ ]:
import numpy as np 
import pandas as pd

m = np. random.randint(1,30, size = (10,3))
df = pd. DataFrame(m, columns = ["var1","var2","var3"])
df

In [ ]:
df[["var1"]]

In [ ]:
df["var1"][0:4]

In [ ]:
df[0:4] [["var1","var2"]]

In [ ]:
df

In [ ]:
df.var1

In [ ]:
df[df.var1 >15]

In [ ]:
df[(df.var1 > 15) & (df.var3 < 5)]

In [ ]:
df[(df.var1 > 15), ["var1","var2"]]

In [ ]:
df.loc[(df.var1 > 15), ["var1","var2"]]

In [ ]:
df[(df.var1 > 15)][["var1","var2"]]

### Birleştirme (join İşlemleri)

In [ ]:
import numpy as np 
import pandas as pd

m = np.random.randint(1,30, size = (5,3))
df1 = pd.DataFrame(m, columns =["var1","var2","var3"]) 
df1.head()

In [ ]:
df2 = df1 + 99
df2

In [ ]:

"""
şuan görüldüğü gibi birleştirme  işlemini yaptı 
ama  şöyle  bir problem var 0'dan 4'e geldi  ve tekrar 0'dan 4' e geldi
bu sorunu Çözmek için ignore_index = True   argümanınını ekleriz
"""
pd.concat([df1, df2])

In [ ]:
pd.concat([df1, df2], ignore_index = True)

In [ ]:
?pd.concat

In [ ]:
df1.columns

In [ ]:
df2.columns = ["var1","var2","deg3"]

In [ ]:
df2

In [ ]:
df1

In [ ]:

"""
burda bir uyarı vermesi gerkiyordu ama  vermedi özellik uyarısı
deg3  iki veri setinde olmadığından dolayı bunu problemli bir
işlemmiş gibi alıgılayıp hata üretmesi gerekiyor.
bunu kısmi bir çözümü var.(join = "inner")
"""
pd.concat([df1, df2])

In [ ]:
pd.concat([df1, df2], join = "inner", ignore_index = True)


#kesişimlerine göre birleştirdi 


In [ ]:
pd.concat([df1, df2.reindex(columns=df1.columns)], axis=0, ignore_index = True)

### İleri Birleştirme İşlemleri

In [ ]:
import pandas as pd 
df1 = pd.DataFrame({'calisanlar': ['Ali', 'Veli', 'Ayse', 'Fatma'],
                   'grup': ['Muhasebe', 'Muhendislik', 'Muhendislik','İk']})

df1

In [ ]:
df2 = pd.DataFrame({'calisanlar': ['Ayse', 'Ali', 'Veli', 'Fatma'],
                   'ilk_giris': [2010, 2009, 2014, 2019]})

df2

In [ ]:
pd.merge(df1,df2)

In [ ]:
# bire bir birleştirme
pd.merge(df1,df2, on = "calisanlar")

In [ ]:
# Çoktan teke 
df3 = pd.merge(df1,df2)
df3

In [ ]:
df4 = pd.DataFrame({'grup': ['Muhasebe', 'Muhendislik', 'İk'], 
                   'mudur': ['Caner','Mustafa', 'Berkcan']})
df4

In [ ]:
pd.merge(df3,df4)

In [ ]:
# Çoktan Çoka

df5 =pd.DataFrame({'grup': ['Muhasebe', 'Muhasebe',
                           'Muhendislik', 'Muhendislik', 'İk', 'İk'],
                  'yetenekler': ['matematik', 'excel', 'kodlama',
                                'linux', 'excel', 'yonetim']})

df5

In [ ]:
df1

In [ ]:
pd.merge(df1,df5)

### Toplulaştırma  ve Gruplama (Aggregation & Grouping)
#### Basit toplulaştırma fonksiyonları:
- `count()`
- `first()`
- `last()`
- `mean()`
- `median()`
- `min()`
- `max()`
- `std()`
- `var()`
- `sum()`


In [ ]:
import  seaborn as sns

In [ ]:
? sns.load_dataset

In [ ]:
df = sns.load_dataset("planets")
df.head()

In [ ]:
df.shape

In [ ]:

# Sadece sayısal sütunları seçme
numeric_df = df.select_dtypes(include=[float, int])

# Sayısal sütunlar üzerinde ortalama hesaplaması
mean_values = numeric_df.mean()
print(mean_values)


In [ ]:
df["mass"].mean()

In [ ]:
# değerleri sayar
df["mass"].count()

In [ ]:
# min değer
df["year"].min()

In [ ]:
# max değer
df["year"].max()

In [ ]:
#  değerleri topla
df["mass"].sum()

In [ ]:
# standart sapması
df["mass"].std()

In [ ]:
#  varyans hesapla
df["mass"].var()

In [ ]:
"""
bütün değişkenler için temel betimsel istatistikler hesaplar. describe()
"""

df.describe()

In [ ]:
df.describe().T

In [ ]:
"""
eğer elimizdeki veri setinin içerisinde eksik değerler olursa 
"""
df.dropna().describe().T

### Grouplama  İşlemleri:
#### gruplama işlemi: veri setinde yer alan kategorik değişkenlerinin guruplarının yaklanması ve bu grupların üzerinde bazı işlemlerin yapılması.

In [ ]:
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                  'veri': [10,11,52,23,43,55]}, columns = ['gruplar','veri'])
df

In [ ]:
df.groupby("gruplar")

In [ ]:
df.groupby("gruplar").sum()

In [ ]:
df = sns.load_dataset("planets")
df.head()
#df.tail()

In [ ]:
df.groupby("method")

In [ ]:
df.groupby("method")["orbital_period"].mean()

In [ ]:
df.groupby("method")["orbital_period"].describe().T

#### İleri Toplulaştırma İşlemleri(Aggregate,filter,transform,apply)  

In [ ]:
import pandas  as pd

df =pd.DataFrame({'gruplar': ['A', 'B', 'C',  'A', 'B', 'C'],
                 'degisken1': [10,23,33,22,11,99],
                 'degisken2': [100,253,333,262,111,969]},
                columns = ['gruplar' ,'degisken1', 'degisken2'])

df

In [ ]:
#aggregate
df.groupby("gruplar").mean()

In [ ]:
"""
groupby'i gönderdik ve dedikki veri setini grouplara böl fakat ben 
öyle bir işlem istiyorumki ne (describe) fonksiyonun bana  verdiği
istatistikleri ne de sadece  mod median gibi istatistikleri kendim 
özellikle istatistik belirtmek istiyorum dedimizde işte bunu aggregate
fonksiyonu ile gerçekleştirebiliriz.

"""
df.groupby("gruplar").aggregate(["min", np.median,max])

In [ ]:
df.groupby("gruplar").aggregate({"degisken1":["min",sum,np.var],"degisken2":[max,np.median,np.std]})

### filter

In [ ]:
import pandas as pd

df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                  'degisken1': [10,23,33,22,11,99],
                  'degisken2': [100,253,333,262,111,969]},
                 columns = ['gruplar', 'degisken1', 'degisken2'])
df

In [ ]:
def filter_func(x):
    return x["degisken1"].std() > 9
    

In [ ]:
df.groupby("gruplar").std()

In [ ]:
df.groupby("gruplar").filter(filter_func)

### transform

In [ ]:
import pandas as pd 

df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A','B', 'C'],
                  'degisken1': [10,23,33,22,11,99],
                  'degisken2': [100,253,333,262,111,969]},
                 columns = ['gruplar', 'degisken1', 'degisken2'])
df

In [ ]:
df["degisken1"]*9

In [ ]:
df_a  = df.iloc[:,1:3]


In [ ]:
df_a.transform(lambda x: (x-x.mean()) / x.std())

### apply
#### dataframein değişkenlerinin üzeründe gezinme yeteneği olan ve aggregation yani toplulaştırma amacıyla kullanılabilecek bir fonksiyondur.


In [ ]:
df = pd.DataFrame({
                  'degisken1': [10,23,33,22,11,99],
                  'degisken2': [100,253,333,262,111,969]},
                 columns = ['degisken1', 'degisken2'])
df

In [ ]:
df.apply(np.sum)

In [ ]:
df.apply(np.mean)

In [ ]:
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A','B', 'C'],
                  'degisken1': [10,23,33,22,11,99],
                  'degisken2': [100,253,333,262,111,969]},
                 columns = ['gruplar', 'degisken1', 'degisken2'])
df

In [ ]:
df.groupby("gruplar").apply(np.mean)

### Pivot Tablolar

In [ ]:
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset("titanic")
titanic.head(7)

In [ ]:
titanic.groupby("sex")["survived"].mean()

In [ ]:
titanic.groupby("sex")[["survived"]].mean()

In [ ]:
titanic.groupby(["sex", "class"])[["survived"]].aggregate("mean")

In [ ]:
# burda unstack() dediğimizde buradaki hiyaraşik 
#index yapısı çözülmüş olur
titanic.groupby(["sex", "class"])[["survived"]].aggregate("mean").unstack()

### pivot ile table

In [ ]:
titanic.pivot_table("survived", index = "sex", columns = "class")

In [ ]:
titanic.age.head()

In [ ]:
age = pd.cut(titanic["age"], [0, 18, 90])
age.head(10)

In [ ]:
titanic.pivot_table("survived", ["sex", age], "class")

### Dış Kaynaklı Veri Okumak 

In [ ]:
import pandas as pd

In [ ]:
?pd.read_csv

#### csv okuma 

In [ ]:
"""
alt satırda yazdığım kodta görüldüğü gibi bir problem var düzgün bir 
şekilde  okunamadı ver okuma işlemlerinde en sık karşılaşan problem 
budur (paylaşılan veri seti genelde [csv ve txt] formatında  olduğunda 
değişkenler bir birlerinden bazı ayraçlar il ayrılır )

ör biz şuanda  read_csv  fonksiyonunu olduğu gibi çalıştırdık ve 
okumasını bekledik fakat ayraç olarak ön tanımlı kullanılan değer
, virgül olduğundan dolayı  bize gelmiş olan bu veri setinindeyse 
ayraç olarak ;(noktalı virgül) kullanıldığından dolayı  okuma işlemi
hatalı oldu.
"""
#pd.read_csv("ornekcsv.csv")
pd.read_csv("ornekcsv.csv",sep = ";")


#### txt okuma  

In [ ]:
pd.read_csv("duz_metin.txt")

### excel okuma

In [ ]:
df = pd.read_excel("ornekx.xlsx")

In [ ]:
type(df)

In [ ]:
df.head()

In [ ]:
df.columns

In [ ]:
df.columns = ("A","B","C")
df

In [ ]:
#  sıfırdan txt okuma
tips = pd.read_csv("data.txt")

In [ ]:
tips.tail()

####  Problem Çözme ve Doküman Okuma Kültürü 